# Site settings
title: "Anton Kuzmenko"
description: "TIL and other stuff"
author: Anton Kuzmenko
url: "https://antonkuzmenko.dev"
baseurl: ""

# Build settings
markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - .github
  - package.json
  - package-lock.json
  - tailwind.config.js
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - Makefile
  - css/tailwind.css

# Permalinks
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Defaults
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      comments: true
      til: false
  -
    scope:
      path: "_posts/tils"
      type: "posts"
    values:
      layout: "post"
      comments: true
      til: true

# License
license: CC-BY-4.0
license_url: https://creativecommons.org/licenses/by/4.0/
