# Site settings
title: "Anton Kuzmenko’s Blog"
description: "TIL and other stuff"
url: "https://antonkuzmenko.dev"
baseurl: ""

author: Anton Kuzmenko

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Permalinks
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      author: Anton Kuzmenko

# License
license: CC-BY-4.0
license_url: https://creativecommons.org/licenses/by/4.0/
